//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tira.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tira.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0} is not recognized..
        /// </summary>
        internal static string CheckRecognitionResultExportAllowed_ErrorMessage {
            get {
                return ResourceManager.GetString("CheckRecognitionResultExportAllowed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any symbols.
        /// </summary>
        internal static string DataColumnType_AnySymbols {
            get {
                return ResourceManager.GetString("DataColumnType_AnySymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty column.
        /// </summary>
        internal static string DataColumnType_EmptyColumn {
            get {
                return ResourceManager.GetString("DataColumnType_EmptyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters only.
        /// </summary>
        internal static string DataColumnType_LettersOnly {
            get {
                return ResourceManager.GetString("DataColumnType_LettersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers only.
        /// </summary>
        internal static string DataColumnType_NumbersOnly {
            get {
                return ResourceManager.GetString("DataColumnType_NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_En {
            get {
                return ResourceManager.GetString("Language_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Language_Ru {
            get {
                return ResourceManager.GetString("Language_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Language_Unknown {
            get {
                return ResourceManager.GetString("Language_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data columns need to be defined..
        /// </summary>
        internal static string ValidateOcr_Messages_NoDataColumns {
            get {
                return ResourceManager.GetString("ValidateOcr_Messages_NoDataColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images loaded..
        /// </summary>
        internal static string ValidateOcr_Messages_NoImages {
            get {
                return ResourceManager.GetString("ValidateOcr_Messages_NoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition rectangle area no set for image {0}.
        /// </summary>
        internal static string ValidateOcr_Messages_RectangleNotSet {
            get {
                return ResourceManager.GetString("ValidateOcr_Messages_RectangleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of vertical lines for image {0}.
        /// </summary>
        internal static string ValidateOcr_Messages_WrongNumberOfVerticalLines {
            get {
                return ResourceManager.GetString("ValidateOcr_Messages_WrongNumberOfVerticalLines", resourceCulture);
            }
        }
    }
}
