//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tira.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tira.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program for extracting data from images containing tables using OCR..
        /// </summary>
        public static string Application_About {
            get {
                return ResourceManager.GetString("Application_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © AkSoftware 2018.
        /// </summary>
        public static string Application_Copyright {
            get {
                return ResourceManager.GetString("Application_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tira - Table Images Recognition Application.
        /// </summary>
        public static string Application_FullName {
            get {
                return ResourceManager.GetString("Application_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Images Recognition Application.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tira.
        /// </summary>
        public static string Application_ShortName {
            get {
                return ResourceManager.GetString("Application_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold:.
        /// </summary>
        public static string BinarizationFilterWindow_Label_Threshold {
            get {
                return ResourceManager.GetString("BinarizationFilterWindow_Label_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binarization.
        /// </summary>
        public static string BinarizationFilterWindow_Title {
            get {
                return ResourceManager.GetString("BinarizationFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions of the blobs to be removed:.
        /// </summary>
        public static string BlobsRemovalFilterWindow_Label_Header {
            get {
                return ResourceManager.GetString("BlobsRemovalFilterWindow_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max height:.
        /// </summary>
        public static string BlobsRemovalFilterWindow_Label_MaxBlobHeight {
            get {
                return ResourceManager.GetString("BlobsRemovalFilterWindow_Label_MaxBlobHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max width:.
        /// </summary>
        public static string BlobsRemovalFilterWindow_Label_MaxBlobWidth {
            get {
                return ResourceManager.GetString("BlobsRemovalFilterWindow_Label_MaxBlobWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min height:.
        /// </summary>
        public static string BlobsRemovalFilterWindow_Label_MinBlobHeight {
            get {
                return ResourceManager.GetString("BlobsRemovalFilterWindow_Label_MinBlobHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min width:.
        /// </summary>
        public static string BlobsRemovalFilterWindow_Label_MinBlobWidth {
            get {
                return ResourceManager.GetString("BlobsRemovalFilterWindow_Label_MinBlobWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blobs removal.
        /// </summary>
        public static string BlobsRemovalFilterWindow_Title {
            get {
                return ResourceManager.GetString("BlobsRemovalFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness:.
        /// </summary>
        public static string BrightnessFilterWindow_Label_Brightness {
            get {
                return ResourceManager.GetString("BrightnessFilterWindow_Label_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string BrightnessFilterWindow_Title {
            get {
                return ResourceManager.GetString("BrightnessFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast:.
        /// </summary>
        public static string ContrastFilterWindow_Label_Contrast {
            get {
                return ResourceManager.GetString("ContrastFilterWindow_Label_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string ContrastFilterWindow_Title {
            get {
                return ResourceManager.GetString("ContrastFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm image cropping area selection..
        /// </summary>
        public static string CropFilterWindow_Label_Header {
            get {
                return ResourceManager.GetString("CropFilterWindow_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string CropFilterWindow_Title {
            get {
                return ResourceManager.GetString("CropFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DataColumnWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("DataColumnWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DataColumnWindow_Button_Save {
            get {
                return ResourceManager.GetString("DataColumnWindow_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string DataColumnWindow_Label_ColumnType {
            get {
                return ResourceManager.GetString("DataColumnWindow_Label_ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string DataColumnWindow_Label_Name {
            get {
                return ResourceManager.GetString("DataColumnWindow_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extra spaces:.
        /// </summary>
        public static string DataColumnWindow_Label_RemoveExtraSpaces {
            get {
                return ResourceManager.GetString("DataColumnWindow_Label_RemoveExtraSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove line breaks:.
        /// </summary>
        public static string DataColumnWindow_Label_RemoveLineBreaks {
            get {
                return ResourceManager.GetString("DataColumnWindow_Label_RemoveLineBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove punctuation:.
        /// </summary>
        public static string DataColumnWindow_Label_RemovePunctuation {
            get {
                return ResourceManager.GetString("DataColumnWindow_Label_RemovePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data column.
        /// </summary>
        public static string DataColumnWindow_Title {
            get {
                return ResourceManager.GetString("DataColumnWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string FilterWindow_Button_Apply {
            get {
                return ResourceManager.GetString("FilterWindow_Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FilterWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("FilterWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FilterWindow_Button_Save {
            get {
                return ResourceManager.GetString("FilterWindow_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma:.
        /// </summary>
        public static string GammaCorrectionFilterWindow_Label_GammaCorrection {
            get {
                return ResourceManager.GetString("GammaCorrectionFilterWindow_Label_GammaCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma correction.
        /// </summary>
        public static string GammaCorrectionFilterWindow_Title {
            get {
                return ResourceManager.GetString("GammaCorrectionFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string IntroductionWindow_Button_CreateProject {
            get {
                return ResourceManager.GetString("IntroductionWindow_Button_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string IntroductionWindow_Button_OpenProject {
            get {
                return ResourceManager.GetString("IntroductionWindow_Button_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent projects:.
        /// </summary>
        public static string IntroductionWindow_Label_RecentProjects {
            get {
                return ResourceManager.GetString("IntroductionWindow_Label_RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string IntroductionWindow_Label_Version {
            get {
                return ResourceManager.GetString("IntroductionWindow_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project opening.
        /// </summary>
        public static string IntroductionWindow_ProjectDoesNotExistMessage_Caption {
            get {
                return ResourceManager.GetString("IntroductionWindow_ProjectDoesNotExistMessage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project does not exists. 
        ///Do you want to remove it from the list?.
        /// </summary>
        public static string IntroductionWindow_ProjectDoesNotExistMessage_Text {
            get {
                return ResourceManager.GetString("IntroductionWindow_ProjectDoesNotExistMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string LineRemoveOrientation_Horizontal {
            get {
                return ResourceManager.GetString("LineRemoveOrientation_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LineRemoveOrientation_None {
            get {
                return ResourceManager.GetString("LineRemoveOrientation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string LineRemoveOrientation_Vertical {
            get {
                return ResourceManager.GetString("LineRemoveOrientation_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line type:.
        /// </summary>
        public static string LinesRemovalFilterWindow_Label_LineOrientation {
            get {
                return ResourceManager.GetString("LinesRemovalFilterWindow_Label_LineOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines removal.
        /// </summary>
        public static string LinesRemovalFilterWindow_Title {
            get {
                return ResourceManager.GetString("LinesRemovalFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing images.
        /// </summary>
        public static string NoImageToRemoveWarning_Caption {
            get {
                return ResourceManager.GetString("NoImageToRemoveWarning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select images to remove..
        /// </summary>
        public static string NoImageToRemoveWarning_Text {
            get {
                return ResourceManager.GetString("NoImageToRemoveWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines markup.
        /// </summary>
        public static string NoRectangleInMarkupWarning_Caption {
            get {
                return ResourceManager.GetString("NoRectangleInMarkupWarning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first set a rectangle area for recognition..
        /// </summary>
        public static string NoRectangleInMarkupWarning_Text {
            get {
                return ResourceManager.GetString("NoRectangleInMarkupWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines markup.
        /// </summary>
        public static string NotEnoughDataGridColumnsInMarkupWarning_Caption {
            get {
                return ResourceManager.GetString("NotEnoughDataGridColumnsInMarkupWarning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first set data columns.
        ///For vertical lines markup data columns quantity must be more than 1..
        /// </summary>
        public static string NotEnoughDataGridColumnsInMarkupWarning_Text {
            get {
                return ResourceManager.GetString("NotEnoughDataGridColumnsInMarkupWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the project. May be it has deprecated format..
        /// </summary>
        public static string OpenProjectErrorMessage {
            get {
                return ResourceManager.GetString("OpenProjectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProjectCreationWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ProjectCreationWindow_Button_Create {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string ProjectCreationWindow_Button_SelectFile {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Button_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill all text fields!.
        /// </summary>
        public static string ProjectCreationWindow_Label_DataInvalid {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Label_DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file:.
        /// </summary>
        public static string ProjectCreationWindow_Label_ProjectFile {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Label_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name:.
        /// </summary>
        public static string ProjectCreationWindow_Label_ProjectName {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project template:.
        /// </summary>
        public static string ProjectCreationWindow_Label_ProjectTemplate {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Label_ProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project creation.
        /// </summary>
        public static string ProjectCreationWindow_ProjectValidationMessage_Caption {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_ProjectValidationMessage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all textboxes are filled..
        /// </summary>
        public static string ProjectCreationWindow_ProjectValidationMessage_Text {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_ProjectValidationMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project creation.
        /// </summary>
        public static string ProjectCreationWindow_Title {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ProjectSettingsWindow_Button_AddDataColumn {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_Button_AddDataColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProjectSettingsWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ProjectSettingsWindow_Button_DeleteDataColumn {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_Button_DeleteDataColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProjectSettingsWindow_Button_EditDataColumn {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_Button_EditDataColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ProjectSettingsWindow_Button_Save {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ProjectSettingsWindow_GridColumn_ColumnTypeName {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_GridColumn_ColumnTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectSettingsWindow_GridColumn_Name {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_GridColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra spaces.
        /// </summary>
        public static string ProjectSettingsWindow_GridColumn_RemoveExtraSpaces {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_GridColumn_RemoveExtraSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line breaks.
        /// </summary>
        public static string ProjectSettingsWindow_GridColumn_RemoveLineBreaks {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_GridColumn_RemoveLineBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation.
        /// </summary>
        public static string ProjectSettingsWindow_GridColumn_RemovePunctuation {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_GridColumn_RemovePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data columns for recognition:.
        /// </summary>
        public static string ProjectSettingsWindow_Label_DataGridLabelText {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_Label_DataGridLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string ProjectSettingsWindow_Title {
            get {
                return ResourceManager.GetString("ProjectSettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string ProjectTemplate_NotSet {
            get {
                return ResourceManager.GetString("ProjectTemplate_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project template.
        /// </summary>
        public static string ProjectTemplateDelete_Caption {
            get {
                return ResourceManager.GetString("ProjectTemplateDelete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete project template?.
        /// </summary>
        public static string ProjectTemplateDelete_Text {
            get {
                return ResourceManager.GetString("ProjectTemplateDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ProjectTemplatesWindow_Button_DeleteProjectTemplate {
            get {
                return ResourceManager.GetString("ProjectTemplatesWindow_Button_DeleteProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProjectTemplatesWindow_Button_EditProjectTemplate {
            get {
                return ResourceManager.GetString("ProjectTemplatesWindow_Button_EditProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectTemplatesWindow_GridColumn_Name {
            get {
                return ResourceManager.GetString("ProjectTemplatesWindow_GridColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects templates list:.
        /// </summary>
        public static string ProjectTemplatesWindow_Label_DataGridLabelText {
            get {
                return ResourceManager.GetString("ProjectTemplatesWindow_Label_DataGridLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects templates.
        /// </summary>
        public static string ProjectTemplatesWindow_Title {
            get {
                return ResourceManager.GetString("ProjectTemplatesWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProjectTemplateWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("ProjectTemplateWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ProjectTemplateWindow_Button_Save {
            get {
                return ResourceManager.GetString("ProjectTemplateWindow_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name should not be empty..
        /// </summary>
        public static string ProjectTemplateWindow_Error_Empty {
            get {
                return ResourceManager.GetString("ProjectTemplateWindow_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with such name already exists..
        /// </summary>
        public static string ProjectTemplateWindow_Error_Exists {
            get {
                return ResourceManager.GetString("ProjectTemplateWindow_Error_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name:.
        /// </summary>
        public static string ProjectTemplateWindow_Label_TemplateName {
            get {
                return ResourceManager.GetString("ProjectTemplateWindow_Label_TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project as template.
        /// </summary>
        public static string ProjectTemplateWindow_Title_CreateTemplate {
            get {
                return ResourceManager.GetString("ProjectTemplateWindow_Title_CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project template.
        /// </summary>
        public static string ProjectTemplateWindow_Title_EditTemplate {
            get {
                return ResourceManager.GetString("ProjectTemplateWindow_Title_EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition.
        /// </summary>
        public static string ProjectWindow_OcrCompletedMessage_Caption {
            get {
                return ResourceManager.GetString("ProjectWindow_OcrCompletedMessage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition successfully competed..
        /// </summary>
        public static string ProjectWindow_OcrCompletedMessage_Text {
            get {
                return ResourceManager.GetString("ProjectWindow_OcrCompletedMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing application.
        /// </summary>
        public static string ProjectWindowClosing_Caption {
            get {
                return ResourceManager.GetString("ProjectWindowClosing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save project data before closing application?.
        /// </summary>
        public static string ProjectWindowClosing_Text {
            get {
                return ResourceManager.GetString("ProjectWindowClosing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom side:.
        /// </summary>
        public static string PunchHolesRemovalFilterWindow_Label_BottomSide {
            get {
                return ResourceManager.GetString("PunchHolesRemovalFilterWindow_Label_BottomSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch holes locations:.
        /// </summary>
        public static string PunchHolesRemovalFilterWindow_Label_Header {
            get {
                return ResourceManager.GetString("PunchHolesRemovalFilterWindow_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left side:.
        /// </summary>
        public static string PunchHolesRemovalFilterWindow_Label_LeftSide {
            get {
                return ResourceManager.GetString("PunchHolesRemovalFilterWindow_Label_LeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right side:.
        /// </summary>
        public static string PunchHolesRemovalFilterWindow_Label_RightSide {
            get {
                return ResourceManager.GetString("PunchHolesRemovalFilterWindow_Label_RightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top side:.
        /// </summary>
        public static string PunchHolesRemovalFilterWindow_Label_TopSide {
            get {
                return ResourceManager.GetString("PunchHolesRemovalFilterWindow_Label_TopSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch holes removal.
        /// </summary>
        public static string PunchHolesRemovalFilterWindow_Title {
            get {
                return ResourceManager.GetString("PunchHolesRemovalFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add images.
        /// </summary>
        public static string Ribbon_Button_AddImages {
            get {
                return ResourceManager.GetString("Ribbon_Button_AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto crop.
        /// </summary>
        public static string Ribbon_Button_AutoResize {
            get {
                return ResourceManager.GetString("Ribbon_Button_AutoResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto rotate.
        /// </summary>
        public static string Ribbon_Button_AutoRotate {
            get {
                return ResourceManager.GetString("Ribbon_Button_AutoRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binarize.
        /// </summary>
        public static string Ribbon_Button_Binarize {
            get {
                return ResourceManager.GetString("Ribbon_Button_Binarize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Ribbon_Button_Brightness {
            get {
                return ResourceManager.GetString("Ribbon_Button_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear markup.
        /// </summary>
        public static string Ribbon_Button_ClearMarkup {
            get {
                return ResourceManager.GetString("Ribbon_Button_ClearMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string Ribbon_Button_Contrast {
            get {
                return ResourceManager.GetString("Ribbon_Button_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilation.
        /// </summary>
        public static string Ribbon_Button_Dilation {
            get {
                return ResourceManager.GetString("Ribbon_Button_Dilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup mode.
        /// </summary>
        public static string Ribbon_Button_EnableMarkup {
            get {
                return ResourceManager.GetString("Ribbon_Button_EnableMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erosion.
        /// </summary>
        public static string Ribbon_Button_Erosion {
            get {
                return ResourceManager.GetString("Ribbon_Button_Erosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string Ribbon_Button_Export {
            get {
                return ResourceManager.GetString("Ribbon_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string Ribbon_Button_Export_Csv {
            get {
                return ResourceManager.GetString("Ribbon_Button_Export_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json.
        /// </summary>
        public static string Ribbon_Button_Export_Json {
            get {
                return ResourceManager.GetString("Ribbon_Button_Export_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Office (ods).
        /// </summary>
        public static string Ribbon_Button_Export_Ods {
            get {
                return ResourceManager.GetString("Ribbon_Button_Export_Ods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel (xls).
        /// </summary>
        public static string Ribbon_Button_Export_Xls {
            get {
                return ResourceManager.GetString("Ribbon_Button_Export_Xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel (xlsx).
        /// </summary>
        public static string Ribbon_Button_Export_Xlsx {
            get {
                return ResourceManager.GetString("Ribbon_Button_Export_Xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit height.
        /// </summary>
        public static string Ribbon_Button_FitHeight {
            get {
                return ResourceManager.GetString("Ribbon_Button_FitHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit size.
        /// </summary>
        public static string Ribbon_Button_FitSize {
            get {
                return ResourceManager.GetString("Ribbon_Button_FitSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit width.
        /// </summary>
        public static string Ribbon_Button_FitWidth {
            get {
                return ResourceManager.GetString("Ribbon_Button_FitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        public static string Ribbon_Button_Gamma {
            get {
                return ResourceManager.GetString("Ribbon_Button_Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal line.
        /// </summary>
        public static string Ribbon_Button_HorizontalLineMarkup {
            get {
                return ResourceManager.GetString("Ribbon_Button_HorizontalLineMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Ribbon_Button_ManualResize {
            get {
                return ResourceManager.GetString("Ribbon_Button_ManualResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string Ribbon_Button_ManualRotate {
            get {
                return ResourceManager.GetString("Ribbon_Button_ManualRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Ribbon_Button_MarkupCopy {
            get {
                return ResourceManager.GetString("Ribbon_Button_MarkupCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Ribbon_Button_MarkupPaste {
            get {
                return ResourceManager.GetString("Ribbon_Button_MarkupPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recognition.
        /// </summary>
        public static string Ribbon_Button_PerformOcr {
            get {
                return ResourceManager.GetString("Ribbon_Button_PerformOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string Ribbon_Button_ProjectSettings {
            get {
                return ResourceManager.GetString("Ribbon_Button_ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Ribbon_Button_RectangleMarkup {
            get {
                return ResourceManager.GetString("Ribbon_Button_RectangleMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blobs.
        /// </summary>
        public static string Ribbon_Button_RemoveBlobs {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemoveBlobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove images.
        /// </summary>
        public static string Ribbon_Button_RemoveImages {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemoveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Ribbon_Button_RemoveLines {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemoveLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        public static string Ribbon_Button_RemoveNoise {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemoveNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveObjects.
        /// </summary>
        public static string Ribbon_Button_RemoveObjects {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemoveObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch holes.
        /// </summary>
        public static string Ribbon_Button_RemovePunchHoles {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemovePunchHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip holes.
        /// </summary>
        public static string Ribbon_Button_RemoveStapleMarks {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemoveStapleMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback all.
        /// </summary>
        public static string Ribbon_Button_RollbackAll {
            get {
                return ResourceManager.GetString("Ribbon_Button_RollbackAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback one step.
        /// </summary>
        public static string Ribbon_Button_RollbackOneStep {
            get {
                return ResourceManager.GetString("Ribbon_Button_RollbackOneStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as template.
        /// </summary>
        public static string Ribbon_Button_SaveAsTemplate {
            get {
                return ResourceManager.GetString("Ribbon_Button_SaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical line.
        /// </summary>
        public static string Ribbon_Button_VerticalLineMarkup {
            get {
                return ResourceManager.GetString("Ribbon_Button_VerticalLineMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string Ribbon_Button_ZoomIn {
            get {
                return ResourceManager.GetString("Ribbon_Button_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string Ribbon_Button_ZoomOut {
            get {
                return ResourceManager.GetString("Ribbon_Button_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Ribbon_GroupBox_Color {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string Ribbon_GroupBox_Correction {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Ribbon_GroupBox_Gallery {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup.
        /// </summary>
        public static string Ribbon_GroupBox_Markup {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Markup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup copy.
        /// </summary>
        public static string Ribbon_GroupBox_MarkupCopy {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_MarkupCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Ribbon_GroupBox_Project {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string Ribbon_GroupBox_Rollback {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Ribbon_GroupBox_Size {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Ribbon_GroupBox_Templates {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Ribbon_GroupBox_Zoom {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Ribbon_MainMenu_About {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Ribbon_MainMenu_Close {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string Ribbon_MainMenu_CreateProject {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Ribbon_MainMenu_Help {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string Ribbon_MainMenu_OpenProject {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project templates.
        /// </summary>
        public static string Ribbon_MainMenu_ProjectTemplates {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_ProjectTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Ribbon_MainMenu_Save {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Ribbon_MainMenu_Settings {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: {0}.
        /// </summary>
        public static string Ribbon_StatusBar_ProjectTitleFormat {
            get {
                return ResourceManager.GetString("Ribbon_StatusBar_ProjectTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with images.
        /// </summary>
        public static string Ribbon_TabGroup_Image {
            get {
                return ResourceManager.GetString("Ribbon_TabGroup_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Ribbon_TabItem_Image {
            get {
                return ResourceManager.GetString("Ribbon_TabItem_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Ribbon_TabItem_Main {
            get {
                return ResourceManager.GetString("Ribbon_TabItem_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        public static string Ribbon_TabItem_Transformation {
            get {
                return ResourceManager.GetString("Ribbon_TabItem_Transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation angle:.
        /// </summary>
        public static string RotationFilterWindow_Label_Angle {
            get {
                return ResourceManager.GetString("RotationFilterWindow_Label_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string RotationFilterWindow_Title {
            get {
                return ResourceManager.GetString("RotationFilterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsWindow__Button_Cancel {
            get {
                return ResourceManager.GetString("SettingsWindow__Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsWindow__Button_Save {
            get {
                return ResourceManager.GetString("SettingsWindow__Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsWindow_Label_Language {
            get {
                return ResourceManager.GetString("SettingsWindow_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string UnexpectedError_Caption {
            get {
                return ResourceManager.GetString("UnexpectedError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred. Please look to the error log..
        /// </summary>
        public static string UnexpectedError_Text {
            get {
                return ResourceManager.GetString("UnexpectedError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception has occurred, application will be terminated.
        /// </summary>
        public static string UnhandledExceptionOccurredApplicationWillBeClosed {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccurredApplicationWillBeClosed", resourceCulture);
            }
        }
    }
}
