//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tira.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tira.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program for extracting data from images containing tables using OCR..
        /// </summary>
        public static string Application_About {
            get {
                return ResourceManager.GetString("Application_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © AkSoftware 2018.
        /// </summary>
        public static string Application_Copyright {
            get {
                return ResourceManager.GetString("Application_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tira - Table Images Recognition Application.
        /// </summary>
        public static string Application_FullName {
            get {
                return ResourceManager.GetString("Application_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Images Recognition Application.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tira.
        /// </summary>
        public static string Application_ShortName {
            get {
                return ResourceManager.GetString("Application_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string IntroductionWindow_Button_CreateProject {
            get {
                return ResourceManager.GetString("IntroductionWindow_Button_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string IntroductionWindow_Button_OpenProject {
            get {
                return ResourceManager.GetString("IntroductionWindow_Button_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent projects:.
        /// </summary>
        public static string IntroductionWindow_Label_RecentProjects {
            get {
                return ResourceManager.GetString("IntroductionWindow_Label_RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string IntroductionWindow_Label_Version {
            get {
                return ResourceManager.GetString("IntroductionWindow_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project opening.
        /// </summary>
        public static string IntroductionWindow_ProjectDoesNotExistMessage_Caption {
            get {
                return ResourceManager.GetString("IntroductionWindow_ProjectDoesNotExistMessage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project does not exists. 
        ///Do you want to remove it from the list?.
        /// </summary>
        public static string IntroductionWindow_ProjectDoesNotExistMessage_Text {
            get {
                return ResourceManager.GetString("IntroductionWindow_ProjectDoesNotExistMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProjectCreationWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ProjectCreationWindow_Button_Create {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string ProjectCreationWindow_Button_SelectFile {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Button_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill all text fields!.
        /// </summary>
        public static string ProjectCreationWindow_Label_DataInvalid {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Label_DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file:.
        /// </summary>
        public static string ProjectCreationWindow_Label_ProjectFile {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Label_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name:.
        /// </summary>
        public static string ProjectCreationWindow_Label_ProjectName {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project creation.
        /// </summary>
        public static string ProjectCreationWindow_ProjectValidationMessage_Caption {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_ProjectValidationMessage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all textboxes are filled..
        /// </summary>
        public static string ProjectCreationWindow_ProjectValidationMessage_Text {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_ProjectValidationMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project creation.
        /// </summary>
        public static string ProjectCreationWindow_Title {
            get {
                return ResourceManager.GetString("ProjectCreationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition.
        /// </summary>
        public static string ProjectWindow_OcrCompletedMessage_Caption {
            get {
                return ResourceManager.GetString("ProjectWindow_OcrCompletedMessage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition successfully competed..
        /// </summary>
        public static string ProjectWindow_OcrCompletedMessage_Text {
            get {
                return ResourceManager.GetString("ProjectWindow_OcrCompletedMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add images.
        /// </summary>
        public static string Ribbon_Button_AddImages {
            get {
                return ResourceManager.GetString("Ribbon_Button_AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string Ribbon_Button_Export {
            get {
                return ResourceManager.GetString("Ribbon_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recognition.
        /// </summary>
        public static string Ribbon_Button_PerformOcr {
            get {
                return ResourceManager.GetString("Ribbon_Button_PerformOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Ribbon_Button_ProjectSettings {
            get {
                return ResourceManager.GetString("Ribbon_Button_ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove images.
        /// </summary>
        public static string Ribbon_Button_RemoveImages {
            get {
                return ResourceManager.GetString("Ribbon_Button_RemoveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Ribbon_GroupBox_Gallery {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Ribbon_GroupBox_Project {
            get {
                return ResourceManager.GetString("Ribbon_GroupBox_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Ribbon_MainMenu_About {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Ribbon_MainMenu_Close {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string Ribbon_MainMenu_CreateProject {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string Ribbon_MainMenu_OpenProject {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Ribbon_MainMenu_Save {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Ribbon_MainMenu_Settings {
            get {
                return ResourceManager.GetString("Ribbon_MainMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: {0}.
        /// </summary>
        public static string Ribbon_StatusBar_ProjectTitleFormat {
            get {
                return ResourceManager.GetString("Ribbon_StatusBar_ProjectTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Ribbon_TabItem_Main {
            get {
                return ResourceManager.GetString("Ribbon_TabItem_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string UnexpectedError_Caption {
            get {
                return ResourceManager.GetString("UnexpectedError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred. Please look to the error log..
        /// </summary>
        public static string UnexpectedError_Text {
            get {
                return ResourceManager.GetString("UnexpectedError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception has occurred, application will be terminated.
        /// </summary>
        public static string UnhandledExceptionOccurredApplicationWillBeClosed {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccurredApplicationWillBeClosed", resourceCulture);
            }
        }
    }
}
